### PR TITLE
Set SWIFT_VERSION to 4.0

### PR DESCRIPTION
**Pull request by eoger**
It looks like XCode 10.2 doesn't support Swift 3.2 anymore, from lockbox-ios:

`error: SWIFT_VERSION '3.2' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'MappaMundi')`

### CODE REVIEW

**Comment by eoger** [comment]
Just realized there's also https://github.com/mozilla-mobile/MappaMundi/pull/8 if you don't mind upgrading to 5.0

**Comment by eoger** [comment]
@garvankeeley r? on this PR or the other one? This blocks lockbox-ios build.

**Comment by garvankeeley** [comment]
This is definitely needed, r+ from me

**Comment by eoger** [comment]
@jhugman do you mind landing this? Neither Garvan nor I have commit access.

**Pull request merged**
